name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: http-pulse on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: test
        run: |
          chmod +x mvnw
          ./mvnw clean test

      - name: build-native
        run: ./mvnw native:compile -Pnative -DskipTests

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: http-pulse-build-${{ matrix.os }}
          path: target/